import {useState} from "react";
import {ArrowRight, CheckCircle, CreditCard, Heart, Minus, Plus, Search, ShieldCheck, ShoppingBag, SlidersHorizontal, Star, Trash2, Truck, X, Menu} from "lucide-react";

export function Header({query,setQuery,mobile,setMobile,wishlistOnly,setWishlistOnly,wishCount,cartCount,setDrawer}) {
  const goTo = id => { setMobile(false); document.getElementById(id)?.scrollIntoView({behavior:"smooth"}); };
  return <header className="nav"><button className="logo logoButton" onClick={()=>goTo("top")}><span>Shop</span>Ease</button>
    <nav className={mobile?"navlinks open":"navlinks"}><button onClick={()=>goTo("shop")}>Shop</button><button onClick={()=>goTo("why")}>Why us</button><button onClick={()=>goTo("about")}>About</button></nav>
    <div className="actions"><div className="searchTop"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products" aria-label="Search products"/></div>
      <button className={wishlistOnly?"heart active":"heart"} onClick={()=>{setWishlistOnly(v=>!v);goTo("shop")}} aria-label="Toggle wishlist" title="Toggle wishlist"><Heart size={19} fill={wishlistOnly?"currentColor":"none"}/>{wishCount>0&&<b>{wishCount}</b>}</button>
      <button className="bag" onClick={()=>setDrawer(true)} aria-label={`Open bag with ${cartCount} items`}><ShoppingBag size={19}/><b>{cartCount}</b></button>
      <button className="menu" onClick={()=>setMobile(!mobile)} aria-label="Toggle navigation">{mobile?<X/>:<Menu/>}</button>
    </div>
  </header>;
}

export function Hero({goTo}) { return <section id="top" className="hero"><div className="heroText"><span className="eyebrow">CURATED FOR EVERYDAY LIFE</span><h1>Good products.<br/><em>Better choices.</em></h1><p>Discover a thoughtfully curated collection of everyday essentials, designed around quality, comfort and modern living.</p><div className="heroBtns"><button className="primary" onClick={()=>goTo("shop")}>Shop collection <ArrowRight size={17}/></button><button className="secondary" onClick={()=>goTo("why")}>Why ShopEase</button></div></div><div className="heroVisual"><div className="circle"></div><div className="heroProduct">NEW<br/><strong>COLLECTION</strong></div><div className="miniCard"><Star fill="currentColor" size={13}/> 4.9 customer rating</div></div></section>; }

export function Benefits() { return <section id="why" className="benefits"><div><Truck/><strong>Fast delivery</strong><small>Quick & reliable shipping</small></div><div><ShieldCheck/><strong>Secure checkout</strong><small>Your data stays protected</small></div><div><RotateCcw/><strong>Easy returns</strong><small>Simple 30-day returns</small></div></section>; }
function RotateCcw(props) { return <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 12a9 9 0 1 0 3-6.7"/><path d="M3 4v5h5"/></svg>; }

export function ProductCard({product,liked,onWish,onAdd,onDetails}) { const [added,setAdded] = useState(false); const handleAdd = () => { onAdd(); setAdded(true); window.setTimeout(()=>setAdded(false),1800); }; return <article className="product"><div className="image"><img src={product.thumbnail} alt={product.title}/><button className={liked?"liked":"like"} onClick={onWish} aria-label={`${liked?"Remove":"Add"} ${product.title} ${liked?"from":"to"} wishlist`}><Heart size={17} fill={liked?"currentColor":"none"}/></button>{product.discountPercentage>0&&<span className="discount">-{Math.round(product.discountPercentage)}%</span>}</div><div className="productBody"><small>{product.category}</small><button className="productTitle" onClick={onDetails}>{product.title}</button><div className="rating"><Star size={13} fill="currentColor"/>{product.rating}</div><div className="bottom"><strong>${product.price}</strong><button className={added?"added":""} onClick={handleAdd}>{added?"Added to bag":"Add to bag"} <Plus size={15}/></button></div></div></article>; }

export function Shop({products,loading,error,retry,cats,category,setCategory,sort,setSort,query,wish,onWish,onAdd,onDetails,wishlistOnly}) { return <section id="shop" className="shop"><div className="heading"><div><span>01 / COLLECTION</span><h2>Find your next favorite.</h2></div><p>{products.length} products</p></div><div className="toolbar"><div className="categoryScroll">{cats.map(c=><button className={category===c?"selected":""} key={c} onClick={()=>setCategory(c)}>{c.replaceAll("-"," ")}</button>)}</div><div className="sort"><SlidersHorizontal size={15}/><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort products"><option value="featured">Featured</option><option value="rating">Top rated</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></div></div>{loading?<div className="loading">Loading collection...</div>:error?<div className="state"><p>We could not load the collection.</p><button className="primary" onClick={retry}>Try again</button></div>:products.length===0?<div className="state"><p>{wishlistOnly?"Your wishlist is empty.":query?"No products match your search.":"No products are available."}</p>{wishlistOnly&&<button className="secondary" onClick={()=>setCategory("all")}>Browse collection</button>}</div>:<div className="grid">{products.map(product=><ProductCard key={product.id} product={product} liked={wish.includes(product.id)} onWish={()=>onWish(product.id)} onAdd={()=>onAdd(product)} onDetails={()=>onDetails(product)}/>)}</div>}</section>; }

export function CartDrawer({cart,total,setDrawer,update,remove,beginCheckout}) { return <><div className="overlay" onClick={()=>setDrawer(false)}></div><aside className="cartDrawer"><div className="cartHead"><h2>Your bag</h2><button onClick={()=>setDrawer(false)} aria-label="Close bag"><X/></button></div>{cart.length===0?<div className="empty"><ShoppingBag size={40}/><p>Your bag is empty.</p><button onClick={()=>setDrawer(false)}>Start shopping</button></div>:<><div className="cartItems">{cart.map(product=><div className="cartItem" key={product.id}><img src={product.thumbnail} alt=""/><div><b>{product.title}</b><small>${product.price}</small><div className="qty"><button onClick={()=>update(product.id,-1)} aria-label="Decrease quantity"><Minus size={13}/></button>{product.qty}<button onClick={()=>update(product.id,1)} aria-label="Increase quantity"><Plus size={13}/></button><button className="remove" onClick={()=>remove(product.id)} aria-label={`Remove ${product.title}`}><Trash2 size={14}/></button></div></div></div>)}</div><div className="checkout"><div><span>Subtotal</span><strong>${total.toFixed(2)}</strong></div><small>Taxes and shipping calculated at checkout.</small><button onClick={beginCheckout}>Proceed to checkout <ArrowRight size={16}/></button></div></>}</aside></>; }

export function ProductModal({product,onClose,onAdd}) { const [added,setAdded] = useState(false); if(!product)return null; const handleAdd = () => { onAdd(product); setAdded(true); window.setTimeout(onClose,500); }; return <div className="modalOverlay" onClick={onClose}><article className="productModal" onClick={e=>e.stopPropagation()}><button className="modalClose" onClick={onClose} aria-label="Close product details"><X/></button><img src={product.thumbnail} alt={product.title}/><div><small>{product.category}</small><h2>{product.title}</h2><div className="rating"><Star size={13} fill="currentColor"/>{product.rating}</div><strong className="modalPrice">${product.price}</strong><p>{product.description||"A carefully selected everyday essential with a thoughtful balance of quality, comfort and modern design."}</p><button className="primary" onClick={handleAdd}>{added?"Added to bag":"Add to bag"} <Plus size={15}/></button></div></article></div>; }

export function Checkout({cart,total,onClose,onComplete}) { const [payment,setPayment] = useState("card"); return <div className="checkoutScreen"><form className="checkoutPanel" onSubmit={onComplete}><div className="checkoutTop"><div><span className="eyebrow">03 / CHECKOUT</span><h2>Complete your order.</h2></div><button type="button" onClick={onClose} aria-label="Close checkout"><X/></button></div><div className="checkoutGrid"><div><h3>Delivery details</h3><div className="formRow"><label>Full name<input required name="name" autoComplete="name" placeholder="Alex Morgan"/></label><label>Email<input required type="email" name="email" autoComplete="email" placeholder="alex@example.com"/></label></div><label>Address<input required name="address" autoComplete="street-address" placeholder="123 Market Street"/></label><div className="formRow"><label>City<input required name="city" autoComplete="address-level2" placeholder="New York"/></label><label>Postal code<input required name="postal" autoComplete="postal-code" placeholder="10001"/></label></div><h3>Payment method</h3><div className="paymentOptions"><label className="paymentOption"><input type="radio" name="payment" value="card" checked={payment==="card"} onChange={()=>setPayment("card")}/><CreditCard size={18}/><span><b>Card payment</b><small>Visa, Mastercard, Amex</small></span></label><label className="paymentOption"><input type="radio" name="payment" value="cash" checked={payment==="cash"} onChange={()=>setPayment("cash")}/><span className="cashIcon">$</span><span><b>Cash on delivery</b><small>Pay when your order arrives</small></span></label></div>{payment==="card"&&<><label>Card number<input required name="card" inputMode="numeric" autoComplete="cc-number" placeholder="4242 4242 4242 4242"/></label><div className="formRow"><label>Expiry<input required name="expiry" placeholder="MM / YY"/></label><label>Security code<input required name="cvc" inputMode="numeric" autoComplete="cc-csc" placeholder="123"/></label></div></>}</div><aside className="orderSummary"><h3>Order summary</h3>{cart.map(p=><div className="summaryItem" key={p.id}><span>{p.title} x {p.qty}</span><strong>${(p.price*p.qty).toFixed(2)}</strong></div>)}<div className="summaryTotal"><span>Total</span><strong>${total.toFixed(2)}</strong></div><small><ShieldCheck size={14}/> Secure demo checkout</small><button type="submit">Place order <ArrowRight size={16}/></button></aside></div></form></div>; }

export function Success({onClose}) { return <div className="successOverlay"><div className="successCard"><CheckCircle size={48}/><span className="eyebrow">ORDER CONFIRMED</span><h2>Thank you for shopping with us.</h2><p>Your demo order has been placed successfully.</p><button onClick={onClose}>Continue shopping <ArrowRight size={16}/></button></div></div>; }
